### PR TITLE
Huge refactor: backends, package layout, ...

### LINKED ISSUE #14: Refactoring
In order to write *unit* tests, I want to extract storing mechanism (`save_mail.go`) from the code and move it into a package. Would you accept such refactoring? Are you ok with [this layouting](https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1)? Thanks :)

### PR DESCRIPTION
**Pull request by remohammadi**
* Packaging of the code is now based on this approach:
  https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1
* Now we can have different backends to store/deliver/process messages
* dummy backend
* logrus for logging (I hadn't a quick way in my mind to keep the server
  log file feature, so I've temporary dropped that feature)
* Makefile, to inject git metadata into the binary (version, build time, ...)
* cobra as the CLI parser
  * serve subcommand
  * version subcommand

Fixes #14

### CODE REVIEW

**Comment by remohammadi** [comment]
To be honest, I haven't tested the `guerrilla-db-redis` backend yet. I'll test it tomorrow 😉

**Comment by flashmob** [comment]
Thanks, that's an impressive effot!
Looks like you're going to collect 3 prizes, one for Testing, Modularize and "fix any tidbits" ones.
The "Standard Package Layout" article is an eye-opener, and very eager to use it. Also good to see logging is improved.
Just had a superficial look so far, will review and test more thoroughly soon.

**Comment by flashmob** [comment]
Was able to build, but not run - seems like goguerrilla.conf.sample doesn't have the latest config, getting this error: Error while loading the backend ""            error="backend \"\" not found"

Some small points:

1. Looks like cobra is a powerful tool, should give more flexibility in the future for managing the server from the command line. The generation of a man page feature is interesting to say the least! As for the 'cmd' folder - perhaps better to call it cli (command line interface)?

2. prepareAllowedHosts() - should that be part of the config package? Because it's read from the config, only the config should be concerned if it's parsed or not, and should provide the already parsed map into the server. This also needs to be reloaded once a SIG-HUP is caught.,(The SIG-HUP config reloading feature needs a lot of work in the future. A related one would be graceful shut down)

3. There is an init() method in each of the backends, could not find where is that called from? 

4. Noticed that the build doesn't complain anymore when there are unused variables, is this something that could be turned on?

5. The Client struct has been placed in the backend.go file and also the readers too. Wouldn't these be more part of their own server.go file (or similar named file)? (Noticed that there is a TODO there, so assuming not yet completed). 

6. How does the version.go work? What is the correct way to use?

7. logrus - excellent choice. So when the logging to a file feature goes back, it would be best to have a separate file per server (like for eg. Nginx does) and a main error log file for general errors (which can be pointed to syslog). Also, really need logurus to work with SIG-HUP so that the logs can be put on rotation)

In all, excellent refactor which should make it more test friendly. It's really good to see this little server grow up :+1:  Looking forward to run it in prod when it's merged!

**Comment by remohammadi** [comment]
Thank you. I hope we (@cafebazaar) also switch to go-guerrilla as our mail server in near future. In that case I guess we'll be happy to alse offer awards for contribution :smile: 

On the points

1. `cmd` seems to have become a convention. You can see that in great projects like [docker](https://github.com/docker/docker/tree/master/cmd) and [kubernetes](https://github.com/kubernetes/kubernetes/tree/master/cmd).
2. You're right. I'll fix it ;)
3. `init` is like `static {}` in java. It's called while the package is loaded. More details: https://golang.org/ref/spec#Package_initialization and http://stackoverflow.com/a/24790378/171732
4. Unused variable [is an error in golang](http://stackoverflow.com/questions/21743841/how-to-avoid-annoying-error-declared-and-not-used-from-golang)! Maybe it was a warning in older versions?
5. For a cleaner Backend, we need to refactor the client a lot. As you and @Xeoncross noted in #14 , I believe we should pack the headers and the connection (or a restricted interface with access to connection), and pass them to the backend. But to keep this refactoring as minimal as possible, I tried to introduce the `backend` mechanism without a huge change in the codes. And yes, the util should not be dependant on `Client` struct. But I guess we can iterate the refactoring in multiple minimal pull requests, to have more control over the changes.
6. The variables inside `version.go` are filled at the [build time](https://www.atatus.com/blog/golang-auto-build-versioning/). They're currently used in the greeting message. To have a more friendly version string, you can tag the git repository on releases, and the `Makefile` will use the tag name instead of the long and unfriendly hash.
7. I can work on it. Is this a blocker for your deployment? As I have mentioned in 5, I'm trying this pull request to not grow more than this. But I understand that your deployment has count on it. :wink: 

And I've found out that I've forgotten to load the config for `GuerrillaDBAndRedisBackend`. I'll fix it and update the pull request very soon.

**Comment by flashmob** [comment]
Thanks for the update.
Sure, you're welcome to offer rewards too.

1. OK, looking at some other projects too - seems like this is the convention. 'cmd' it is then.

2 & 3. Thanks!

4. Ahh, yes, updated the go version recently.

5. Good that we are all on the same page.

6. Thanks.

7. Not really a blocker, since the stdout can be redirected to a logfile. On Guerrilla mail, the SIG_HUP is used only to reload the allowed host list. Save it for another pull request.


Thanks - indeed, it looks like config not loaded for GuerrillaDBAndRedisBackend.

**Comment by flashmob** [comment]
Added you to collaborators; you're welcome to work on this repo instead of your fork.

**Comment by flashmob** [comment]
Hi @remohammadi, could you please provide an update on your status? Looking to merge this soon, so that more work can continue.

**Comment by remohammadi** [comment]
Sorry I was so busy :(

There is still one step before merging: reload after SIGHUP. But it's a bit complicated. To support the reload completely, we have to kill the listening servers, and relisten (to support changes in `servers` and  `servers.listen_interface`. I don't know how to that without nanoseconds of downtime. any idea?

**Comment by flashmob** [comment]
Thanks for the update!
That's OK, will work on the reload after sighup in another branch.
For now, don't need complete reload support.
Yes, how to do it is not trivial as you have noted.
The SIGHUP should not cause any disconnection to established connections,
but a slight pause would be acceptable (if can't be avoided).
The way to change the interface would be to start listening on new one
first then stop accepting from the old one. Disconnect all clients on the
old one if not in DATA state or at end of DATA state (graceful shutdown).
Then completely stop the server once all clients disconnected.
We also need a graceful shutdown function that will also notify the backend
to stop our workers to close any session / connection / files it may need
to close or perform any other shutdown work.
The SIGHUP handler function would need to work out what needs to be
reloaded & then notify whch parts to shutdown/init..
We also need to reload our ssl config if it changed.
Once this is merged, would like to do a quick experiment on this.

**Comment by remohammadi** [comment]
I've also found [this](https://github.com/fvbock/endless). But it doesn't support changing of ports.

I'm adding a graceful shutdown function to the backend interface. After that, I guess the code is ready for merge.

**Comment by remohammadi** [comment]
I guess it's now ready to be merged. I tested it using [this script](https://github.com/turbodog/python-smtp-mail-sending-tester/blob/master/smtptest.py) with the dummy backed. Can you please test the `GuerrillaDBAndRedisBackend` and check if it's storing the email the way it's supposed to do? 😄 

To summarize the notable behavioral changes from the main branch:

* Reloaded config is not applied 😞 
* The log outputs are not separated based on the server configs
* The format of configuration is changed to support different backends

**Comment by flashmob** [comment]
Merged! 
Going to try it out on Guerrilla Mail soon.
Thank you for your contribution - very much appreciated!

**Pull request merged**
