### PR TITLE
Fix for issue #66: If loading the certificate fails

### PR DESCRIPTION
**Pull request by dapaxx**
either don't advertise STARTTLS or with TLS only disable the server

### CODE REVIEW

**Comment by flashmob** [comment]
Just wondering, do other servers shut down when the new certificate is bad? Maybe it should not apply the config, and continue using the old.

**Comment by dapaxx** [comment]
On a reload most servers just silently continue with the old configuration. they only complain on a restart. 
I'll have a look into the reload and how to warn the user if a bad (or missing) cert is about to be loaded.

Although mainly this should affect disabling STARTTLS. "Pure" SMTPS servers are pretty rare nowadays, they are mostly only used for MUA access - and even here it is usual to use SMTP Submission on port 587. SMTPS 465 is pretty much deprecated.

**Comment by flashmob** [comment]
Sorry it's taking longer to merge the fix.
Currently refactoring some things - would like to avoid changing the config values there - these should always reflect the values on the file otherwise be immutable, and the validation should be done earlier.

**Comment by flashmob** [comment]
So the new behaviour is:

- guerrillad will not start if it can't load a certificate

- If already started and a config is reloaded with a bad certificate, it will ignore the new config and continue with the old one.

**Comment by flashmob** [comment]
@dapaxx - is this new behaviour ok to merge?

**Pull request merged**
