### PR TITLE
Issues #195 to #201

### PR DESCRIPTION
**Pull request by flashmob**
Fixes a few issues (see commits)

### CODE REVIEW

**Comment by flashmob** [comment]
- Parser captures quoted local-parts without the escape characters
- mail.Address.String() know when to quote local-part, 
- server's `allowsHost` function is ipv6 address aware (addresses specified in the config will get normalized to their ipv6 simplest form, addresses parsed from RCPT and MAIL commands will have ipv6 normalized)
- if `<postmaster>` is used in the RCPT TO (without a host), then new functionality was added to assume that the host is assumed to be the Hostname setting for the Server
- HELO/EHLO argument validation. #200
- The “header” processor populates “Received:” headers wrongly. #198
-  tiny bug in “p_redis.go”. #196
- “MimeHeaderDecode” (envelope.go) returns an incorrectly-spaced string. #195
- go-guerrilla cannot properly handle some valid addresses. #199

**Comment by flashmob** [comment]
ping @issuefiler

**Comment by issuefiler** [comment]
pong @flashmob.

Sorry, I think I’m a bit late to the cognac party.
Just updated my build to the latest and checked the new changes out. It looks good to me, too!
Thank you for the update.

**Comment by flashmob** [comment]
Thanks for checking in!

The latest master has been deployed on Guerrilla Mail too, so it's going through the ultimate battle test right now. Cheers!

**Pull request merged**
