### PR TITLE
dep

### PR DESCRIPTION
**Pull request by athoune**
Using dep, not glide.

### CODE REVIEW

**Comment by athoune** [comment]
Sorry for the battle with Travis.

**Comment by flashmob** [comment]
That's ok. Thanks for the contribution!

Will update to dep soon, your PR means it will be sooner 😀

**Comment by jamestbrown** [comment]
👍 👍

**Comment by dvcrn** [comment]
Luckily `dep init` is already capable converting a glide project over to dep so this hopefully should be pretty simple 👍

**Comment by ThisIsAreku** [comment]
Any news about this MR ?

**Comment by flashmob** [comment]
@ThisIsAreku Thanks for the reminder. Yes, it will be merged soon. For now, If you're using dep, you may try the `dep init` option for converting from glide as suggested above, or merge in this branch to your fork.

**Comment by dvcrn** [comment]
> For now, If you're using dep, you may try the `dep init` option for converting from glide as suggested above

I’ve been doing this for my usecase without any issues

**Comment by lord-alfred** [comment]
@athoune, @flashmob 
Readme and https://github.com/flashmob/go-guerrilla/wiki/Build-Notes already contains text about glide

**Comment by flashmob** [comment]
Thanks! Updated.

**Comment by lord-alfred** [comment]
But readme not updated :)
https://github.com/flashmob/go-guerrilla#dependencies
https://github.com/flashmob/go-guerrilla#1-import-the-guerrilla-package

**Comment by flashmob** [comment]
Thanks! Will update the readme soon (or you can beat me to it and submit a
PR if you like!)

**Pull request merged**
